name: schooldynamics
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutx:
    path: ./flutx
  connectivity_plus: ^3.0.2
  dio: ^4.0.4
  google_fonts: ^2.3.2
  #provider: ^6.0.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Base Dependencies
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.2.0
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.3.0
  url_launcher: ^6.1.9
  flutter_native_splash: ^2.1.6
  geolocator: ^9.0.2
  image_picker: ^0.8.6+1
  shimmer: ^2.0.0
  intl: ^0.17.0
  onesignal_flutter: ^3.5.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1

  get: ^4.6.5
  sqflite: ^2.2.4+1
  shared_preferences: ^2.0.17



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.2
  change_app_package_name: ^1.0.0




  # Icons
  material_design_icons_flutter: ^6.0.7096
  flutter_feather_icons: ^2.0.0+1
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/login/
    - assets/images/logo.png
