name: schooldynamics
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.21+21

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # internet_connection_checker: ^1.0.0+1
  dio: ^4.0.4
  google_fonts: ^6.1.0
  #provider: ^6.0.2

  # Base Dependencies
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.4.1
  flutter_form_builder: 9.6.0
  form_builder_validators: 11.1.1
  url_launcher: ^6.3.1
#  flutter_native_splash: ^2.4.4
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  intl: ^0.20.1
  flutx: ^0.2.0-rc.4

  get: ^4.6.6
  sqflite: ^2.4.1
  shared_preferences: ^2.3.4
  share_plus: ^10.1.3
  fluttertoast: ^8.2.4
  onesignal_flutter: 5.2.9
  #  loading_animation_widget: ^1.2.0+4
  syncfusion_flutter_pdfviewer: 28.1.36
  flutter_html: ^3.0.0-beta.2
  in_app_update: ^4.2.3
#  qr_code_scanner: ^1.0.1
  #  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  signature: ^5.5.0
  path_provider: ^2.1.5
  flutter_easyloading: ^3.0.5
  sqflite_common_ffi_web: ^0.4.5+4
  internet_connection_checker_plus: ^2.6.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  country_code_picker: ^3.1.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

dependency_overrides:
  intl: any
  google_fonts: any

  # Icons
  material_design_icons_flutter: ^7.0.7296
  flutter_feather_icons: ^2.0.0+1
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/login/
    - assets/images/logo.png
